[package]
authors = ["too-r <william@huddie.net>"]
name = "sudobot-rs"
version = "0.1.0"
[dependencies]
lazy_static = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serenity = "*"
spin = "*"
toml = "*"
