array_layout = "Block"
wrap_comments = true
error_on_line_overflow = false
format_strings = true
max_width = 200 # Helps to ensure long lines are formatted if possible
reorder_imported_names = true
reorder_imports = true

